version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    ports:
      - "${APP_FORWARD_PORT}:80"
    volumes:
      - .:/var/www/html

  node:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - .:/app

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_FORWARD_PORT}:3306"
    volumes:
      - db_data:/var/lib/mysql

  mail:
    image: axllent/mailpit
    ports:
      - "${MAIL_FORWARD_PORT}:1025"
      - "${MAIL_WEB_FORWARD_PORT}:8025"

volumes:
  db_data:
